#!/usr/bin/env bash
set -e
BOLD=$(tput bold)
DIM=$(tput dim)
GREEN=$(tput setaf 2)
CYAN=$(tput setaf 6)
YELLOW=$(tput setaf 3)
MAGENTA=$(tput setaf 5)
BLUE=$(tput setaf 4)
RESET=$(tput sgr0)

clear
echo "${GREEN}${BOLD}  TERMINAL PORTFOLIO${RESET}"
echo "${BOLD}  Prabhat Mishra${RESET}"
echo "${DIM}  Software Developer${RESET}"
echo ""
echo "${CYAN}  About${RESET}"
echo "  Software Developer specializing in the TypeScript/Node.js ecosystem,"
echo "  building privacy-first, scalable SaaS products with a focus on operational"
echo "  reliability and long-term cost-efficiency."
echo "  I work across the full stack — from database design and backend APIs to"
echo "  responsive frontend interfaces — preferring to own features end-to-end."
echo "  Most of what I build is shaped by one question: does this stay fast and cost"
echo "  less as it scales?"
echo ""
echo "${CYAN}  Skills${RESET}"
echo "  ${YELLOW}Languages   ${RESET}${BOLD}TypeScript${RESET} ${BOLD}JavaScript${RESET} ${BOLD}Python${RESET} ${BOLD}Go${RESET}"
echo "  ${YELLOW}Backend     ${RESET}${BOLD}Node.js${RESET} ${BOLD}Bun${RESET} ${BOLD}Elysia${RESET} ${BOLD}Express${RESET} ${BOLD}Hono${RESET} ${BOLD}FastAPI${RESET} ${BOLD}Flask${RESET} ${BOLD}Socket.io${RESET}"
echo "  ${YELLOW}Frontend    ${RESET}${BOLD}React${RESET} ${BOLD}Next.js${RESET} ${BOLD}Angular${RESET} ${BOLD}Redux${RESET} ${BOLD}Zustand${RESET} ${BOLD}ShadcnUI${RESET} ${BOLD}TailwindCSS${RESET} ${BOLD}FramerMotion${RESET} ${BOLD}FfmpegWASM${RESET}"
echo "  ${YELLOW}Databases   ${RESET}${BOLD}MongoDB${RESET} ${BOLD}PostgreSQL${RESET} ${BOLD}SQLite${RESET} ${BOLD}Redis${RESET} ${BOLD}Prisma${RESET} ${BOLD}Drizzle${RESET}"
echo "  ${YELLOW}Dev / Tools ${RESET}${BOLD}Cloudflare${RESET} ${BOLD}Docker${RESET} ${BOLD}Git${RESET} ${BOLD}Postman${RESET} ${BOLD}Cloudinary${RESET} ${BOLD}Vercel${RESET}"
echo ""
echo "${CYAN}  Projects${RESET}"
echo "  ${GREEN}1.${RESET} ${BOLD}rum-core${RESET}"
echo "    Full-stack RUM SaaS capturing Core Web Vitals and API timing via a"
echo "    lightweight browser script. Built on a pre-aggregation pipeline across 34"
echo "    Turso/SQLite tables with a Bun/Elysia + Cloudflare Workers backend and"
echo "    Next.js dashboard."
echo "  ${DIM}Stack:${RESET} ${YELLOW}TypeScript${RESET} ${YELLOW}Elysia${RESET} ${YELLOW}Hono${RESET} ${YELLOW}Next.js${RESET} ${YELLOW}PostgreSQL${RESET} ${YELLOW}SQLite${RESET} ${YELLOW}Redis${RESET} ${YELLOW}Drizzle${RESET} ${YELLOW}Cloudflare${RESET} ${YELLOW}Docker${RESET}"
echo "  ${DIM}Links:${RESET} ${BLUE}Live${RESET}: https://rum-core.prabhatlabs.dev  ${BLUE}GitHub${RESET}: https://github.com/prabhatlabs/rum-core"
echo ""
echo "  ${GREEN}2.${RESET} ${BOLD}Blade Tools${RESET}"
echo "    Suite of 20+ privacy-first, browser-based tools for PDF, image, and video"
echo "    processing. Leverages FFmpeg WASM for client-side media transcoding — zero"
echo "    uploads, zero server costs."
echo "  ${DIM}Stack:${RESET} ${YELLOW}TypeScript${RESET} ${YELLOW}Next.js${RESET} ${YELLOW}TailwindCSS${RESET} ${YELLOW}ShadcnUI${RESET} ${YELLOW}FfmpegWASM${RESET}"
echo "  ${DIM}Links:${RESET} ${BLUE}Live${RESET}: https://bladetools.prabhatlabs.dev  ${BLUE}GitHub${RESET}: https://github.com/prabhatlabs"
echo ""
echo "${CYAN}  Experience${RESET}"
echo "  ${BOLD}Glück Global Pvt Ltd      ${RESET}${DIM}May 2026 - Present${RESET}"
echo "  ${MAGENTA}Full Stack Developer    ${RESET}${DIM}Remote${RESET}"
echo "  ${DIM}TypeScript${RESET} ${DIM}JavaScript${RESET} ${DIM}MongoDB${RESET} ${DIM}Express${RESET} ${DIM}Angular${RESET} ${DIM}Socket.io${RESET}"
echo ""
echo "  ${BOLD}Freelance                 ${RESET}${DIM}Feb 2026 - Mar 2026${RESET}"
echo "  ${MAGENTA}Full Stack Developer (Next.js)${RESET}${DIM}Remote${RESET}"
echo "  ${DIM}TypeScript${RESET} ${DIM}Bun${RESET} ${DIM}Next.js${RESET} ${DIM}Elysia${RESET} ${DIM}PostgreSQL${RESET} ${DIM}Zustand${RESET} ${DIM}FramerMotion${RESET} ${DIM}ShadcnUI${RESET} ${DIM}TailwindCSS${RESET}"
echo ""
echo "  ${BOLD}Flexzistay                ${RESET}${DIM}Oct 2025 - Dec 2025${RESET}"
echo "  ${MAGENTA}Software Developer Intern${RESET}${DIM}Remote${RESET}"
echo "  ${DIM}TypeScript${RESET} ${DIM}Node.js${RESET} ${DIM}Express${RESET} ${DIM}Next.js${RESET} ${DIM}PostgreSQL${RESET} ${DIM}Redis${RESET} ${DIM}Cloudinary${RESET} ${DIM}TailwindCSS${RESET} ${DIM}Git${RESET}"
echo ""
echo "  ${BOLD}NxTechWorks Consulting    ${RESET}${DIM}Jan 2025 - Sep 2025${RESET}"
echo "  ${MAGENTA}Full Stack Developer Intern${RESET}${DIM}Remote${RESET}"
echo "  ${DIM}JavaScript${RESET} ${DIM}Python${RESET} ${DIM}Node.js${RESET} ${DIM}FastAPI${RESET} ${DIM}Express${RESET} ${DIM}MongoDB${RESET} ${DIM}SQLite${RESET} ${DIM}PostgreSQL${RESET} ${DIM}React${RESET} ${DIM}Redux${RESET} ${DIM}Git${RESET}"
echo ""
echo "  ${BOLD}TecoNico Pvt. Ltd.        ${RESET}${DIM}Jul 2024 - Dec 2024${RESET}"
echo "  ${MAGENTA}Full Stack Developer Intern${RESET}${DIM}Remote${RESET}"
echo "  ${DIM}JavaScript${RESET} ${DIM}Node.js${RESET} ${DIM}Express${RESET} ${DIM}MongoDB${RESET} ${DIM}Git${RESET}"
echo ""
echo "${CYAN}  Contact${RESET}"
echo "  ${GREEN}x             ${RESET} https://x.com/prabhatlabs"
echo "  ${GREEN}github        ${RESET} https://github.com/prabhatlabs"
echo "  ${GREEN}linkedin      ${RESET} https://linkedin.com/in/prabhatm8000"
echo "  ${GREEN}mail          ${RESET} mailto:prabhatm8000@gmail.com"
echo "  ${GREEN}buymeacoffee  ${RESET} https://www.buymeacoffee.com/prabhatlabs"
echo "  ${GREEN}instagram     ${RESET} https://instagram.com/prabhatm8000"
echo ""
echo "${DIM}curl https://prabhatlabs.dev/cli.sh | bash${RESET}"